services:
  postgres:
    image: postgres:13
    container_name: ppt-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-presentation_gen_db}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: ppt-redis
    ports:
      - "16379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: ppt-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - minio_data:/data
      - ${PPT_OUTPUT_VOLUME:-./data/output}:/minio-output
      - ${PPT_SLIDES_VOLUME:-./data/slides}:/minio-slides
    command: server /data --console-address ":9001"
    restart: unless-stopped

  create-minio-buckets:
    image: minio/mc
    container_name: ppt-create-minio-buckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      /usr/bin/mc mb myminio/ingest || true;
      /usr/bin/mc mb myminio/output || true;
      /usr/bin/mc mb myminio/voice-clones || true;
      /usr/bin/mc mb myminio/presentations || true;
      exit 0;
      "
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: ppt-api
    container_name: ppt-api
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "18000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-presentation_gen_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    restart: unless-stopped

  worker_cpu:
    build:
      context: .
      dockerfile: docker/worker_cpu/Dockerfile
    image: ppt-worker-cpu
    container_name: ppt-worker_cpu
    depends_on:
      - redis
      - minio
      - libreoffice
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-presentation_gen_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - LIBREOFFICE_HOST=libreoffice
    restart: unless-stopped

  worker_gpu:
    build:
      context: .
      dockerfile: docker/worker_gpu/Dockerfile
    image: ppt-worker-gpu
    container_name: ppt-worker_gpu
    depends_on:
      - redis
      - minio
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-presentation_gen_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    runtime: ${GPU_RUNTIME:-runc}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-1}
              capabilities: [gpu]
    restart: unless-stopped

  libreoffice:
    build:
      context: .
      dockerfile: docker/libreoffice/Dockerfile
    image: ppt-libreoffice
    container_name: ppt-libreoffice
    ports:
      - "18100:8100"
    environment:
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
